server:
  port: 8080

security:
  jwt:
    issuer: "http://localhost:8081"
    ttl-seconds: 1800
    private-key-path: ${JWT_PRIVATE_KEY_PATH:/run/secrets/auth/private.pem}
    public-key-path: ${JWT_PUBLIC_KEY_PATH:/run/secrets/auth/public.pem}

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:banksim_auth}
    username: ${DB_USER:banksim}
    password: ${DB_PASSWORD:banksim}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:banksim}
    password: ${RABBIT_PASSWORD:banksim}

account-service:
  base-url: ${ACCOUNT_SERVICE_BASE_URL:http://account-service:8080}
