server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8081}
          jwk-set-uri: ${JWT_JWK_SET_URI:http://auth-service:8080/.well-known/jwks.json}
  application:
    name: gateway
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-jwks
              uri: http://auth-service:8080
              predicates:
                - Path=/.well-known/jwks.json

            - id: auth
              uri: http://auth-service:8080
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

            - id: account
              uri: http://account-service:8080
              predicates:
                - Path=/account/**
              filters:
                - StripPrefix=1
