spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:banksim_account}
    username: ${DB_USER:banksim}
    password: ${DB_PASSWORD:banksim}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:banksim}
    password: ${RABBIT_PASSWORD:banksim}
